(function initializeRetailStores(root, factory) {
  const stores = factory();
  root.RetailStores = stores;
  if (typeof module === 'object' && module.exports) module.exports = stores;
}(typeof globalThis !== 'undefined' ? globalThis : this, () => [
  ['Beleza na Web', 'https://www.belezanaweb.com.br/'],
  ['Época Cosméticos', 'https://www.epocacosmeticos.com.br/'],
  ['Amo Beleza', 'https://www.amobeleza.com.br/'],
  ['Danny Cosméticos', 'https://www.dannycosmeticos.com.br/'],
  ['ElaUsa Cosméticos', 'https://elausa.com.br/'],
  ['Seiki Perfumaria', 'https://www.seiki.com.br/'],
  ['Doce Beleza', 'https://www.docebeleza.com.br/'],
  ['The Beauty Box', 'https://www.thebeautybox.com.br/'],
  ['Lemis Store', 'https://www.lemisstore.com.br/'],
  ['Cabelos na Web', 'https://www.cabelosnaweb.com.br/'],
  ['Ikesaki', 'https://www.ikesaki.com.br/'],
  ['Sumirê', 'https://www.sumire.com.br/'],
  ['Lojas Rede', 'https://www.lojasrede.com.br/'],
  ['Perfumaria Kennedy', 'https://www.perfumariakennedy.com.br/'],
  ['Perfumaria Primor', 'https://www.primor.com.br/'],
  ['Mercado Livre', 'https://www.mercadolivre.com.br/'],
  ['Amazon Brasil', 'https://www.amazon.com.br/'],
  ['Shopee Brasil', 'https://shopee.com.br/'],
  ['Magazine Luiza', 'https://www.magazineluiza.com.br/'],
  ['Casas Bahia', 'https://www.casasbahia.com.br/'],
  ['Ponto', 'https://www.ponto.com.br/'],
  ['Carrefour', 'https://www.carrefour.com.br/'],
  ['Americanas', 'https://www.americanas.com.br/'],
  ['Drogasil', 'https://www.drogasil.com.br/'],
  ['Droga Raia', 'https://www.drogaraia.com.br/'],
  ['Pague Menos', 'https://www.paguemenos.com.br/'],
  ['Panvel', 'https://www.panvel.com/'],
  ['Drogaria São Paulo', 'https://www.drogariasaopaulo.com.br/'],
  ['Drogarias Pacheco', 'https://www.drogariaspacheco.com.br/'],
  ['Ultrafarma', 'https://www.ultrafarma.com.br/'],
  ['Farmácias Nissei', 'https://www.farmaciasnissei.com.br/'],
  ['Pão de Açúcar', 'https://www.paodeacucar.com/'],
  ['Extra', 'https://www.clubeextra.com.br/'],
  ['Angeloni', 'https://www.angeloni.com.br/'],
  ['Coop', 'https://www.coopsp.com.br/'],
  ['Hair Fly', 'https://www.hairfly.com.br/'],
  ['Loja dos Cabelos', 'https://www.lojadoscabelos.com.br/'],
  ['Shop dos Cabelos', 'https://www.shopdoscabelos.com.br/'],
  ['Lívia Cosméticos', 'https://www.liviacosmeticos.com.br/'],
  ['Goya Perfumaria', 'https://www.goya.com.br/'],
  ['Casa Costa Cosméticos', 'https://www.casacosta.com.br/'],
  ['Monamie Cosméticos', 'https://www.monamie.com.br/'],
  ['Tokyo Cosméticos', 'https://www.tokyocosmeticos.com.br/'],
  ['Beauty Fair Shop', 'https://loja.beautyfair.com.br/'],
  ['Kutiz Beauté', 'https://www.kutiz.com.br/'],
  ['Cosmetic Center', 'https://www.cosmeticcenter.com.br/'],
  ['Belshop', 'https://www.belshop.com.br/'],
  ['Meu Cabelo Natural', 'https://www.meucabelonatural.com.br/'],
  ['Lojas Renner', 'https://www.lojasrenner.com.br/'],
  ['Riachuelo', 'https://www.riachuelo.com.br/'],
  ['Olist Shops', 'https://www.olist.com/'],
  ['Shoppe Cosméticos', 'https://www.shoppecosmeticos.com.br/'],
  ['Perfumaria em Casa', 'https://www.perfumariaemcasa.com.br/'],
  ['NocNoc', 'https://www.nocnoc.com.br/'],
  ['Mercado Shops', 'https://www.mercadoshops.com.br/'],
  ['Use Orgânico', 'https://www.useorganico.com.br/'],
  ['Évora Cosméticos', 'https://www.evoracosmeticos.com.br/'],
  ['Cosméticos Online', 'https://www.cosmeticosonline.com.br/'],
  ['Top Cosméticos', 'https://www.topcosmeticos.com.br/'],
  ['Vale Cosméticos', 'https://www.valecosmeticos.com.br/'],
  ['Mundo do Cabeleireiro', 'https://www.mundodocabeleireiro.com.br/'],
  ['Rio Bel Cosméticos', 'https://www.riobel.com.br/'],
  ['Perfumaria Coral', 'https://www.perfumariacoral.com.br/'],
  ['Super Nosso', 'https://www.supernosso.com/'],
  ['Atacadão', 'https://www.atacadao.com.br/'],
  ["Sam's Club", 'https://www.samsclub.com.br/'],
  ['Assaí', 'https://www.assai.com.br/'],
  ['Savegnago', 'https://www.savegnago.com.br/'],
  ['Mambo', 'https://www.mambo.com.br/'],
  ['Oba Hortifruti', 'https://www.obahortifruti.com.br/']
].map(([name, url]) => ({ name, url, host: new URL(url).hostname.replace(/^www\./, '') }))));
